apiVersion: v1
kind: Service
metadata:
  name: jira-to-slack
  namespace: jira-to-slack
  labels:
    app: jira-to-slack
spec:
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30003
  selector:
    app: jira-to-slack
  type: NodePort
