apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira-to-slack
  namespace: jira-to-slack
  labels:
    app: jira-to-slack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jira-to-slack
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jira-to-slack
    spec:
      containers:
      - image: int128/jira-to-slack:v1.9.0
        name: jira-to-slack
        ports:
        - containerPort: 3000
